spring:
  datasource:
    url: jdbc:h2:mem:testdb  # base en memoria, si querés archivo cambiás mem por file
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true               # activa la consola web
      path: /h2-console           # url de acceso a la consola
  jpa:
    hibernate:
      ddl-auto: update            # puede ser create, create-drop, update o validate
    show-sql: true                # muestra las consultas en consola
    properties:
      hibernate:
        format_sql: true          # formatea las consultas en consola