server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supermercado
    username: root
    password: Cuenta.1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  # Configuración del formato de fechas para JPA
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: UTC
